version: '3.8'

services:
  ai-lunch-learn-frontend:
    build: .
    container_name: ai-lunch-learn-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ai-lunch-learn-net


networks:
  ai-lunch-learn-net:
    driver: bridge